export class HandleGenerator {
  private readonly nouns = [
    "pilgrim",
    "monk",
    "candle",
    "prayer",
    "incense",
    "psalter",
    "icon",
    "cross",
    "bell",
    "dome",
    "altar",
    "chapel",
    "censer",
    "vestment",
    "scroll",
    "iconostasis",
    "chalice",
    "komboskini",
    "bible",
    "gospel",
    "liturgy",
    "hymn",
    "chant",
    "ison",
    "humility",
    "pascha",
    "epiphany",
    "epistle",
    "vespers",
    "orthros",
    "compline",
    "paraklesis",
    "vigil",
    "hours",
    "ekklesia",
    "synaxis",
    "theosis",
    "saint",
    "martyr",
    "farmer",
    "elder",
    "monastic",
    "abbot",
    "archimandrite",
    "archpriest",
    "protopresbyter",
    "hermit",
    "deacon",
    "priest",
    "bishop",
    "archbishop",
    "patriarch",
    "father",
    "son",
    "brother",
    "sister",
    "monastery",
    "hermitage",
    "skete",
    "psalter",
    "triodion",
  ];

  private readonly adjectives = [
    "humble",
    "blessed",
    "pious",
    "devout",
    "reverent",
    "silent",
    "peaceful",
    "ancient",
    "mystical",
    "holy",
    "faithful",
    "graceful",
    "radiant",
    "steadfast",
    "wise",
    "saintly",
    "virtuous",
    "zealous",
    "godly",
    "divine",
    "eternal",
    "sacred",
    "celestial",
    "ascetic",
    "prayerful",
    "liturgical",
    "hesychastic",
    "iconographic",
    "monastic",
    "theological",
    "mystical",
    "apostolic",
    "patristic",
    "sacramental",
    "chanting",
    "ascetical",
    "canonical",
    "ecclesiastical",
    "noetic",
    "transcendent",
    "paschal",
    "dogmatic",
    "eucharistic",
    "incarnate",
    "contemplative",
  ];

  public generateHandle(): string {
    const handle = [
      this.getRandomWord(this.adjectives),
      this.getRandomWord(this.nouns),
      this.getRandomWord(this.adjectives),
      this.getRandomWord(this.nouns),
    ].join("-");
    console.log(
      `generated 1 handle out of ${
        (this.adjectives.length *
          this.nouns.length) ** 2
      } possible handles: ${handle}`,
    );

    return handle.toLowerCase();
  }

  private getRandomWord(array: string[]): string {
    return array[Math.floor(Math.random() * array.length)];
  }
}
